version: '3.8'

services:
  twitter-parser:
    build:
      context: crawler
      dockerfile: Dockerfile
      args:
        TWITTER_BEARER_TOKEN: ${TWITTER_BEARER_TOKEN}
        NEO4J_URI: ${NEO4J_URI}
        NEO4J_NAME: ${NEO4J_NAME}
        NEO4J_PASS: ${NEO4J_PASS}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASS: ${REDIS_PASS}
    container_name: twitter-parser
    command: python -m main
    depends_on:
      - redis
    ports:
      - "5000:5000"

  rq-worker:
    build:
      context: crawler
      dockerfile: Dockerfile
      args:
        TWITTER_BEARER_TOKEN: ${TWITTER_BEARER_TOKEN}
        NEO4J_URI: ${NEO4J_URI}
        NEO4J_NAME: ${NEO4J_NAME}
        NEO4J_PASS: ${NEO4J_PASS}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASS: ${REDIS_PASS}
    container_name: rq-worker
    command: python -m workers.default
    depends_on:
      - redis

  neo4j:
    image: neo4j:4.4.5-community
    container_name: neo4j
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_NAME}/${NEO4J_PASS}
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
    volumes:
      - $HOME/neo4j_data:/data
    tty: true

  redis:
    image: redis:7.0.5-alpine
    restart: always
    hostname: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --save 20 1 --loglevel warning --port ${REDIS_PORT} --requirepass ${REDIS_PASS}
    # volumes:
    #   - redis:/data
# volumes:
#   redis:
#     driver: local
