version: '3.8'

services:
  twitter-parser:
    build:
      context: crawler
      dockerfile: Dockerfile
      args:
        APP_URI: ${APP_URI}
        TWITTER_BEARER_TOKEN: ${TWITTER_BEARER_TOKEN}
        NEO4J_URI: ${NEO4J_URI}
        NEO4J_NAME: ${NEO4J_NAME}
        NEO4J_PASS: ${NEO4J_PASS}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASS: ${REDIS_PASS}
    container_name: twitter-parser
    command: python -m main
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - app:/data

  workers:
    build:
      context: crawler
      dockerfile: Dockerfile
      args:
        APP_URI: ${APP_URI}
        TWITTER_BEARER_TOKEN: ${TWITTER_BEARER_TOKEN}
        NEO4J_URI: ${NEO4J_URI}
        NEO4J_NAME: ${NEO4J_NAME}
        NEO4J_PASS: ${NEO4J_PASS}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASS: ${REDIS_PASS}
    container_name: workers
    command: celery -A crawler.use_cases.tasks.tasks worker -l info -c 7
    depends_on:
      - redis

  redis:
    image: redis:7.0.5-alpine
    restart: always
    hostname: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --save 20 1 --loglevel warning --port ${REDIS_PORT} --requirepass ${REDIS_PASS}

volumes:
  app:
    external: false
