version: '3.8'

services:
  twitter-parser:
    build:
      context: crawler
      dockerfile: Dockerfile
      args:
        TWITTER_BEARER_TOKEN: ${TWITTER_BEARER_TOKEN}
        NEO4J_URI: ${NEO4J_URI}
        NEO4J_NAME: ${NEO4J_NAME}
        NEO4J_PASS: ${NEO4J_PASS}
    container_name: twitter-parser
    ports:
      - "5000:5000"
  neo4j:
    image: neo4j:4.4.5-community
    container_name: neo4j
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_NAME}/${NEO4J_PASS}
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
    volumes:
      - $HOME/neo4j_data:/data
    tty: true
